{
  "id": "user_status",
  "fields": [
    {
      "id": "climate_up",
      "type": "text"
    },
    {
      "id": "light_up",
      "type": "text"
    },
    {
      "id": "power_up",
      "type": "text"
    },
    {
      "id": "security_up",
      "type": "text"
    },
    {
      "id": "climate_down",
      "type": "text"
    },
    {
      "id": "light_down",
      "type": "text"
    },
    {
      "id": "power_down",
      "type": "text"
    },
    {
      "id": "security_down",
      "type": "text"
    },
    {
      "id": "skill_exception",
      "type": "exception",
      "is_answer": true
    },
    {
      "id": "http_error",
      "type": "http_error",
      "is_answer": true
    }
  ]
}
