{
    "id": "add_service",
    "fields":
    [
        {
            "id": "add_skill_name",
            "type": "skill_name",
            "must_resolve": true,
            "required": true
        },
        {
            "id": "skill_exception",
            "type": "exception"
        },
        {
            "id": "http_error",
            "type": "http_error"
        }
    ]
}
