{
    "id": "change_service",
    "fields":
    [
        {
            "id": "change_skill_name",
            "type": "skill_name",
            "must_resolve": true,
            "required": true
        }
    ]
}
