{
    "id": "tv_listings",
    "fields": [
        {
          "id": "channel",
          "type": "tv_channel_name"
        },
        {
          "id": "zipcode",
          "type": "us_postal_code",
          "persist": "zipcode"
        },
        {
          "id": "channel_number",
          "type": "number"
        },
        {
          "id": "streaming_service",
          "type": "tv_streaming_service"
        },
        {
          "id": "date",
          "type": "date"
        },
        {
          "id": "time",
          "type": "time"
        },
        {
          "id": "genre",
          "type": "tv_genre"
        },
                {
          "id": "type",
          "type": "tv_type"
        },
        {
          "id": "timerange",
          "type": "time_range"
        },
        {
          "id": "tv_listing",
          "type": "list",
          "item_types": ["program_event"]
        },
        {
          "id": "skill_exception",
          "type": "exception"
        }
    ]
}