{
    "id": "tv_show_airings",
    "fields": [
        {
          "id": "show",
          "type": "tv_show_name",
          "from_context": true
        },
        {
          "id": "skill_exception",
          "type": "exception"
        },
        {
          "id": "tv_listing",
          "type": "list",
          "item_types": ["program_event"]
        }
    ]
}
