{
    "id": "tv_streaming_search",
    "fields": [

        {
          "id": "show",
          "type": "tv_show_name",
          "from_context": true
        },
        {
          "id": "streaming_service",
          "type": "tv_streaming_service"
        },

        {
          "id": "tv_listing",
          "type": "list",
          "item_types": ["program"]
        },
        {
          "id": "skill_exception",
          "type": "exception"
        }
    ]
}