{
    "id": "tv_show_episode_summary",
    "fields": [
        {
          "id": "show",
          "type": "tv_show_name",
 	      "from_context": true
        },
        {
          "id": "episode",
          "type": "episode"
        },
        {
          "id": "season",
          "type": "season"
        },
        {
          "id": "showrelative",
          "type": "showrelative"
        },
        {
          "id": "skill_exception",
          "type": "exception"
        },
        {
          "id": "tv_listing",
          "type": "list",
          "item_types": ["program_event"]
        }
    ]
}