{
  "id": "status",
  "fields": [
    {
      "id": "name",
      "type": "text"
    },
    {
      "id": "group",
      "type": "text"
    },
    {
      "id": "type",
      "type": "text"
    },
    {
      "id": "name_group",
      "type": "alias",
      "alias_for": ["name", "group"],
      "create_from_aliased_field": false
    },
    {
      "id": "name_type",
      "type": "alias",
      "alias_for": ["name", "type"],
      "create_from_aliased_field": false
    },
    {
      "id": "type_group",
      "type": "alias",
      "alias_for": ["type", "group"],
      "create_from_aliased_field": false
    },
    {
      "id": "name_group_type",
      "type": "alias",
      "alias_for": ["name", "group", "type"],
      "create_from_aliased_field": false
    },
    {
      "id": "status",
      "type": "text"
    },
    {
      "id": "all",
      "type": "text"
    },
    {
      "id": "devices",
      "type": "list<device>",
      "is_answer": true
    },
    {
      "id": "skill_exception",
      "type": "exception",
      "is_answer": true
    },
    {
      "id": "http_error",
      "type": "http_error",
      "is_answer": true
    }
  ]
}