{
  "id": "volume_control",
  "fields": [
    {
      "id": "volume_up",
      "type": "text"
    },
    {
      "id": "volume_down",
      "type": "text"
    },
    {
      "id": "volume_max",
      "type": "text"
    },
    {
      "id": "volume_min",
      "type": "text"
    },
    {
      "id": "volume_level",
      "type": "number",
      "must_resolve": true
    },
    {
      "id": "volume_incremental",
      "type": "number"
    },
    {
      "id": "volume_control",
      "type": "volume_control"
    }
  ]
}