{
  "id": "business_phone",
  "fields": [
    {"id": "business",
      "type": "local_business",
      "must_resolve": true,
      "from_context": true
    },
    {
     "id": "business_phone",
     "type": "phone_number"
    }
  ]
}

