{
  "id": "restaurant_search",
  "fields": [
    {
      "id": "location",
      "type": "address",
      "must_resolve": true,
      "black_list": ["hungry"]
    },
    {"id": "cuisine",
      "type": "cuisine"
    },
    {"id": "price",
      "type": "text"
    },
    {"id": "sort_by",
      "type": "text"
    },
    {
      "id": "restaurant_listings",
      "type": "list",
      "item_types": ["local_business"]
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}
