{
  "id": "proactive_hints",
  "fields": [
    {
      "id": "artist",
      "type": "music_artist"
    },
    {
      "id": "artists",
      "type": "list",
      "item_types": ["music_artist"]
    },
    {
      "id": "hints",
      "is_answer": true,
      "type": "list"
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}
