{
  "id": "weather_find",
  "fields": [
    {
      "id": "place_or_day",
      "type": "alias",
      "required": true,
      "alias_for": ["weather_date_range", "location"],
      "must_resolve": true
    },
    {
        "id": "location",
        "type": "address",
        "must_resolve": true
    },
    {
        "id": "weather_date_range",
        "type": "datetime_range",
        "must_resolve": true
    },
    {
      "id": "weather_time",
      "type": "time",
      "must_resolve" : true
    },
    {
      "id": "date_range",
      "type": "alias",
      "must_resolve" : true,
      "alias_for": ["weather_date_range"]
    },
    {
      "id": "weather_find_condition",
      "type": "weather_condition",
      "must_resolve" : true
    },
    {
      "id": "weather_report",
      "type": "weather_report",
      "is_answer": true
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}

