{
  "id": "set_alarm",
  "fields": [
    {"id": "alarm_recurring",
      "type": "yes_no"
    },
    {"id": "alarm_date",
      "type": "date",
      "must_resolve": false
    },
    {"id": "alarm_time",
      "type": "time",
      "must_resolve": false
    }
  ]
}
