{
  "id": "transport_taxi_ride_history",
  "fields": [
    {
      "id": "taxi_service_id",
      "type": "transport_taxi_service_type"
    },
    {
       "id": "ride_history",
       "type": "list",
       "is_answer": true,
       "item_types": ["transport_ride"]
    },
    {
       "id": "skill_exception",
       "type": "exception"
    },
    {
       "id": "http_error",
       "type": "http_error"
    }
  ]
}
