ALTER TABLE music_artists ADD PRIMARY KEY (id);
ALTER TABLE music_albums ADD PRIMARY KEY (id);
ALTER TABLE music_tracks ADD PRIMARY KEY (id);
ALTER TABLE music_albums ADD FOREIGN KEY(artist_id) references music_artists(id);
ALTER TABLE music_tracks ADD FOREIGN KEY(artist_id) references music_artists(id);
ALTER TABLE music_tracks ADD FOREIGN KEY(album_id) references music_albums(id);
CREATE INDEX ON music_artists (name);
CREATE INDEX ON music_albums (name);
CREATE INDEX ON music_tracks (name);
CREATE INDEX ON music_albums (artist_id);
CREATE INDEX ON music_tracks (album_id);
CREATE INDEX ON music_tracks (artist_id);
CREATE INDEX music_tracks_name_gin_trgm_idx ON music_tracks USING gin (name gin_trgm_ops);
CREATE INDEX music_albums_name_gin_trgm_idx ON music_albums USING gin (name gin_trgm_ops);
CREATE INDEX music_artists_name_gin_trgm_idx ON music_artists USING gin (name gin_trgm_ops);
