{
  "id": "sports_follow_a_game",
  "fields": [
    {
      "id": "team_name1",
	  "must_resolve" : true,
      "black_list": ["recent","latest","last","current","division","conference"],
      "type": "sports_team"
    },
    {
      "id": "team_name2",
      "must_resolve" : true,
      "type": "sports_team",
      "black_list": ["recent","latest","last","current","division","conference"]
    },
	{
      "id": "gameTime",
      "must_resolve" : true,
      "type": "time"
    },
	{
      "id": "gameDay",
      "must_resolve" : true,
      "type": "date"
    },
	{
      "id": "gameVenue",
      "must_resolve" : true,
      "type": "venue_name"
    },
	{
      "id": "gameTrigger",
      "must_resolve" : true,
      "type": "text"
    },
	{
      "id": "game_season",
      "must_resolve" : true,
      "type": "season_name"
    },
	{
      "id": "game_player",
      "must_resolve" : true,
      "type": "player_name"
    },
	{
      "id": "game_division",
      "must_resolve" : true,
      "type": "division_name"
    },
	{
      "id": "game_conference",
      "must_resolve" : true,
      "type": "conference_name"
    },
	{
      "id": "gameTournamentOrSports",
      "must_resolve" : true,
      "type": "league_name",
      "black_list": ["league"]
    },
    {
      "id": "sports_data",
      "type": "list",
      "item_types": ["sports_data"]
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}
