{
  "id": "music_replay",
  "fields": [
    {
      "id": "artist",
      "type": "music_artist",
      "use_head_entities": true
    },
    {
      "id": "album",
      "type": "music_album"
    },
    {
      "id": "album_artist",
      "type": "alias",
      "alias_for": ["album", "artist"]
    },
    {
      "id": "collection",
      "type": "music_collection"
    },
    {
      "id": "time_range",
      "type": "datetime_range"
    },
    {
      "id": "tracks",
      "type": "list",
      "item_types": ["music_track"],
      "is_answer": true
    },
    {
      "id": "other_tracks",
      "type": "list",
      "item_types": ["music_track"],
      "is_answer": true
    }
  ]
}
