{
  "id": "music_info_concerts",
  "fields": [
    {
      "id": "artist",
      "type": "music_artist",
      "from_context": true,
      "use_head_entities": true
    },
    {
      "id": "location",
      "type": "address",
      "synth_type": "city_type"
    },
    {
      "id": "venue",
      "type": "text"
    },
    {
      "id": "date",
      "type": "DateTime",
      "synth_type": "common_date"
    },
    {
      "id": "concerts",
      "type": "list",
      "is_answer": true,
      "item_types": ["music_concert"]
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}
