{
  "id": "music_id",
  "fields": [
    {
      "id": "song",
      "type": "music_track",
      "from_context": true,
      "must_resolve": true
    }
  ],
  "context_resolution": {
    "order": ["background", "display"],
    "background_order": ["music"]
  }
}