{
  "id": "music_collection_view",
  "fields": [
    {
      "id": "collections",
      "type": "list",
      "is_answer": true,
      "item_types": ["music_collection"],
      "from_context": true
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}