{
  "id": "music_info_similar_artists",
  "fields": [
    {
      "id": "artist",
      "type": "music_artist",
      "from_context": true,
      "use_head_entities": true
    },
    {
      "id": "artists",
      "type": "list",
      "is_answer": true,
      "item_types": ["music_artist"]
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}
