{
  "id": "music_albums",
  "fields": [
    {
      "id": "artist",
      "type": "music_artist",
      "from_context": true,
      "use_head_entities": true
    },
    {
      "id": "genre",
      "type": "music_genre"
    },
    {
      "id": "era",
      "type": "music_era"
    },
    {
      "id": "albums",
      "is_answer": true,
      "type": "list",
      "item_types": ["music_album"]
    },
    {
      "id": "skill_exception",
      "type": "exception"
    },
    {
      "id": "http_error",
      "type": "http_error"
    }
  ]
}
